In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df1 = pd.read_csv('Ecommerce_Sales_Data.csv')

In [24]:

df2 = pd.read_csv('Retail_Sales_Data.csv')

In [3]:
df1.head()

,Order ID,Order Date,Customer Name,Region,Category,Product Name,Quantity,Sales,Profit,Ship Mode,Payment Type
0,1000,2023-01-13,Alex Morgan,North,Clothing,Jacket Z,12,217284,33197.21,Standard,Credit Card
1,1001,2023-12-06,Morgan Scott,South,Electronics,Laptop X,7,287154,67084.01,Express,Debit Card
2,1002,2024-02-05,Jamie Carter,South,Clothing,Dress K,8,292616,58747.56,Express,Cash
3,1003,2025-08-09,Chris Evans,West,Furniture,Chair Set,8,778560,174062.22,Express,Credit Card
4,1004,2023-06-19,Morgan Scott,East,Electronics,Phone Y,5,473270,40715.95,Standard,Debit Card

In [4]:
df1.describe()

          Order ID    Quantity         Sales         Profit
count   300.000000  300.000000  3.000000e+02     300.000000
mean   1149.500000    7.316667  3.526130e+05   61768.318500
std      86.746758    4.089679  2.915482e+05   59012.798646
min    1000.000000    1.000000  1.829000e+03     304.660000
25%    1074.750000    4.000000  1.197098e+05   16760.170000
50%    1149.500000    7.000000  2.763245e+05   45243.890000
75%    1224.250000   11.000000  5.220555e+05   88002.070000
max    1299.000000   15.000000  1.390065e+06  367841.000000

In [5]:
df1.duplicated().sum()

np.int64(0)

In [6]:
df1.isnull().sum()

Order ID         0
Order Date       0
Customer Name    0
Region           0
Category         0
Product Name     0
Quantity         0
Sales            0
Profit           0
Ship Mode        0
Payment Type     0
dtype: int64

In [25]:
df2.head()

,Date,Region,Category,Product Name,Salesperson,Quantity,Sales Amount,Discount,Profit
0,2023-06-03,South,Furniture,Sofa,David Wilson,6,472452,0.05,113582.13
1,2023-12-26,West,Furniture,Table,Michael Brown,16,777232,0.16,156101.55
2,2025-01-20,East,Clothing,Shirt,Sarah Johnson,16,1222352,0.09,304168.19
3,2025-08-15,East,Furniture,Sofa,Emily Davis,4,122596,0.14,29288.25
4,2023-11-24,North,Furniture,Bookshelf,John Smith,11,379951,0.10,52790.59

In [17]:
df2.dtypes

Date            datetime64[ns]
Region                  object
Category                object
Product Name            object
Salesperson             object
Quantity                 int64
Sales Amount             int64
Discount               float64
Profit                 float64
dtype: object

In [12]:
# change date to datetime format
df2['Date'] = pd.to_datetime(df2['Date'])

In [16]:
# quantity sales profit should be numeric
df2['Quantity'] = pd.to_numeric(df2['Quantity'], errors='coerce')
df2['Sales Amount'] = pd.to_numeric(df2['Sales Amount'], errors='coerce')
df2['Profit'] = pd.to_numeric(df2['Profit'], errors='coerce')

In [26]:
# total sum = sum(sales) column
df2['Total Sum'] = df2['Sales Amount'].sum()
# profit margin = profit / sales
df2['Profit Margin'] = df2['Profit'] / df2['Sales Amount']

In [27]:
# save dfs as excel files
df1.to_excel('Ecommerce_Sales_Data.xlsx', index=False)
df2.to_excel('Retail_Sales_Data.xlsx', index=False)